// Writes neon-database/migrations/0002_seed_demo.sql from the same simulated data
// the demo uses. Run with: npm run db:generate-seed
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { buildSeed, type SeedData } from '../lib/providers/database/seed'

const q = (value: string | null) => (value === null ? 'null' : `'${value.replace(/'/g, "''")}'`)
const n = (value: number | null) => (value === null ? 'null' : String(value))
const ts = (date: Date) => `'${date.toISOString()}'`

function values<T>(rows: T[], toRow: (row: T) => string): string {
  return rows.map((row) => `  (${toRow(row)})`).join(',\n')
}

function chunked<T>(rows: T[], size: number): T[][] {
  const out: T[][] = []
  for (let i = 0; i < rows.length; i += size) out.push(rows.slice(i, i + size))
  return out
}

function insertMany<T>(table: string, columns: string, rows: T[], toRow: (row: T) => string): string {
  return chunked(rows, 500)
    .map(
      (batch) =>
        `insert into ${table} (${columns})\nvalues\n${values(batch, toRow)}\non conflict do nothing;\n`,
    )
    .join('\n')
}

function render(seed: SeedData): string {
  const parts: string[] = [
    '-- 0002_seed_demo.sql',
    '-- Simulated demo data. Generated by scripts/generate-seed.ts; do not edit by hand.',
    '-- Safe to re-run: duplicate rows are skipped.',
    '',
    insertMany(
      'tanks',
      'id, name, site, latitude, longitude, capacity_litres, roof_area_m2',
      seed.tanks,
      (t) => `${q(t.id)}, ${q(t.name)}, ${q(t.site)}, ${n(t.latitude)}, ${n(t.longitude)}, ${n(t.capacityLitres)}, ${n(t.roofAreaM2)}`,
    ),
    insertMany(
      'greywater_units',
      'id, name, site, status, latitude, longitude',
      seed.greywaterUnits,
      (u) => `${q(u.id)}, ${q(u.name)}, ${q(u.site)}, ${q(u.status)}, ${n(u.latitude)}, ${n(u.longitude)}`,
    ),
    insertMany(
      'rainfall_readings',
      'site, recorded_at, rainfall_mm',
      seed.rainfall,
      (r) => `${q(r.site)}, ${ts(r.recordedAt)}, ${n(r.rainfallMm)}`,
    ),
    insertMany(
      'tank_readings',
      'tank_id, recorded_at, level_percent, litres_harvested, litres_used',
      seed.tankReadings,
      (r) => `${q(r.tankId)}, ${ts(r.recordedAt)}, ${n(r.levelPercent)}, ${n(r.litresHarvested)}, ${n(r.litresUsed)}`,
    ),
    insertMany(
      'greywater_readings',
      'unit_id, recorded_at, litres_collected, litres_filtered, litres_reused, filter_pressure_kpa',
      seed.greywaterReadings,
      (r) =>
        `${q(r.unitId)}, ${ts(r.recordedAt)}, ${n(r.litresCollected)}, ${n(r.litresFiltered)}, ${n(r.litresReused)}, ${n(r.filterPressureKpa)}`,
    ),
    insertMany(
      'river_reports',
      'category, description, latitude, longitude, photo_url, reporter_name, status, created_at',
      seed.reports,
      (r) =>
        `${q(r.category)}, ${q(r.description)}, ${n(r.latitude)}, ${n(r.longitude)}, ${q(r.photoUrl)}, ${q(r.reporterName)}, ${q(r.status)}, ${ts(r.createdAt)}`,
    ),
    insertMany(
      'community_activities',
      'kind, title, occurred_on, youth_count, households_reached, facilities_count, trees_planted, participants',
      seed.activities,
      (a) =>
        `${q(a.kind)}, ${q(a.title)}, ${q(a.occurredOn)}, ${n(a.youthCount)}, ${n(a.householdsReached)}, ${n(a.facilitiesCount)}, ${n(a.treesPlanted)}, ${n(a.participants)}`,
    ),
    insertMany(
      'stakeholders',
      'name, organisation_type, role, influence, interest, latitude, longitude',
      seed.stakeholders,
      (s) =>
        `${q(s.name)}, ${q(s.organisationType)}, ${q(s.role)}, ${n(s.influence)}, ${n(s.interest)}, ${n(s.latitude)}, ${n(s.longitude)}`,
    ),
    insertMany(
      'devices',
      'id, tank_id, key_hash',
      seed.devices,
      (d) => `${q(d.id)}, ${q(d.tankId)}, ${q(d.keyHash)}`,
    ),
  ]
  return parts.join('\n')
}

const outputPath = join(process.cwd(), 'neon-database', 'migrations', '0002_seed_demo.sql')
writeFileSync(outputPath, render(buildSeed()), 'utf8')
console.log(`Wrote ${outputPath}`)
